# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bf3f6088905787ef78fe0123f7ae9efe14ee238c5a3d9f1f2d27375716b8878274ae557251d32116d7b54d30455c52a1412bdb23d35f2489abb458ca71e1f9b

test:
  secret_key_base: 0673595b80f64e03b4daf6f509534260979dc43a6f8a92a127b90a0f504fb4b61452d57eac7961b964802ef49b32fd4f86f919f823a121a9bbd9858cad243909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
